# ... test job config

staging-deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: AWS Deploy push
      uses: ItsKarma/aws-cli@v1.70.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-2"
      with:
        args: >-
          deploy push
          --application-name api-server
          --description "This is a revision for the api-server"
          --ignore-hidden-files
          --s3-location s3://deployments/staging-api-server.zip
          --source .
    - name: AWS Create Deploy
      uses: ItsKarma/aws-cli@v1.70.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-2"
      with:
        args: >-
          deploy create-deployment
          --application-name api-server
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name staging
          --file-exists-behavior OVERWRITE
          --s3-location bucket=deployments,key=staging-api-server.zip,bundleType=zip
