name: CI/CD

on: 
 push:
  branches: [ development ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: list all the files
      run: pwd
    - name: Install npm dependencies
      run: ls .
